# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/ClassTemplate.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/AndroidStatus.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/AppLauncher.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/ApplicationWindowSize.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/Backlight.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/BatteryManager.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/BatterySavingMode.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/BluetoothWatcher.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/CalendarUpcomingEvents.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/CellularTechnologies.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/CountryCode.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/DataRoaming.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/DebugToken.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/DeviceProperties.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/FacedownAndPickup.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/FileSystem.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/FontSettings.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/FullscreenPid.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/HardwareInventory.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/HubWatch.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/LanguageAndInput.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/PaymentMethod.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/PhoneActive.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/PhysicalButtons.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/ProgressStatus.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/RadioManager.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/ReconditionInfo.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/Smartwatch.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/SystemSettings.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/TimeZone.qml) \
        $$quote($$BASEDIR/assets/QmlAccessor/WifiWatcher.qml) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/AndroidStatus/AndroidStatus.cpp) \
        $$quote($$BASEDIR/src/ApplicationWindowSize/ApplicationWindowSize.cpp) \
        $$quote($$BASEDIR/src/Backlight/Backlight.cpp) \
        $$quote($$BASEDIR/src/BatteryManager/BatteryManager.cpp) \
        $$quote($$BASEDIR/src/BatterySavingMode/BatterySavingMode.cpp) \
        $$quote($$BASEDIR/src/BluetoothWatcher/BluetoothWatcher.cpp) \
        $$quote($$BASEDIR/src/CalendarUpcomingEvents/CalendarUpcomingEvents.cpp) \
        $$quote($$BASEDIR/src/CellularTechnologies/CellularTechnologies.cpp) \
        $$quote($$BASEDIR/src/CountryCode/CountryCode.cpp) \
        $$quote($$BASEDIR/src/DataRoaming/DataRoaming.cpp) \
        $$quote($$BASEDIR/src/DebugToken/DebugToken.cpp) \
        $$quote($$BASEDIR/src/DeviceProperties/DeviceProperties.cpp) \
        $$quote($$BASEDIR/src/FacedownAndPickup/FacedownAndPickup.cpp) \
        $$quote($$BASEDIR/src/FileSystem/FileSystem.cpp) \
        $$quote($$BASEDIR/src/FontSettings/FontSettings.cpp) \
        $$quote($$BASEDIR/src/FullscreenPid/FullscreenPid.cpp) \
        $$quote($$BASEDIR/src/HardwareInventory/HardwareInventory.cpp) \
        $$quote($$BASEDIR/src/HubWatch/HubWatch.cpp) \
        $$quote($$BASEDIR/src/LanguageAndInput/LanguageAndInput.cpp) \
        $$quote($$BASEDIR/src/PaymentMethod/PaymentMethod.cpp) \
        $$quote($$BASEDIR/src/Pebble/Serializer.cpp) \
        $$quote($$BASEDIR/src/Pebble/Talk2WatchApi.cpp) \
        $$quote($$BASEDIR/src/PhoneActive/PhoneActive.cpp) \
        $$quote($$BASEDIR/src/PhysicalButtons/PhysicalButtons.cpp) \
        $$quote($$BASEDIR/src/PpsWatch/PpsWatch.cpp) \
        $$quote($$BASEDIR/src/ProgressStatus/ProgressStatus.cpp) \
        $$quote($$BASEDIR/src/RadioManager/RadioManager.cpp) \
        $$quote($$BASEDIR/src/ReconditionInfo/ReconditionInfo.cpp) \
        $$quote($$BASEDIR/src/SystemSettings/SystemSettings.cpp) \
        $$quote($$BASEDIR/src/TimeZone/TimeZone.cpp) \
        $$quote($$BASEDIR/src/WifiWatcher/WifiWatcher.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/AndroidStatus/AndroidStatus.h) \
        $$quote($$BASEDIR/src/AppLauncher/AppLauncher.h) \
        $$quote($$BASEDIR/src/ApplicationWindowSize/ApplicationWindowSize.h) \
        $$quote($$BASEDIR/src/Backlight/Backlight.h) \
        $$quote($$BASEDIR/src/BatteryManager/BatteryManager.h) \
        $$quote($$BASEDIR/src/BatterySavingMode/BatterySavingMode.h) \
        $$quote($$BASEDIR/src/BluetoothWatcher/BluetoothWatcher.h) \
        $$quote($$BASEDIR/src/CalendarUpcomingEvents/CalendarUpcomingEvents.h) \
        $$quote($$BASEDIR/src/CellularTechnologies/CellularTechnologies.h) \
        $$quote($$BASEDIR/src/CountryCode/CountryCode.h) \
        $$quote($$BASEDIR/src/DataRoaming/DataRoaming.h) \
        $$quote($$BASEDIR/src/DebugToken/DebugToken.h) \
        $$quote($$BASEDIR/src/DeviceProperties/DeviceProperties.h) \
        $$quote($$BASEDIR/src/FacedownAndPickup/FacedownAndPickup.h) \
        $$quote($$BASEDIR/src/FileSystem/FileSystem.h) \
        $$quote($$BASEDIR/src/FontSettings/FontSettings.h) \
        $$quote($$BASEDIR/src/FullscreenPid/FullscreenPid.h) \
        $$quote($$BASEDIR/src/HardwareInventory/HardwareInventory.h) \
        $$quote($$BASEDIR/src/HubWatch/HubWatch.h) \
        $$quote($$BASEDIR/src/LanguageAndInput/LanguageAndInput.h) \
        $$quote($$BASEDIR/src/PaymentMethod/PaymentMethod.h) \
        $$quote($$BASEDIR/src/Pebble/Serializer.h) \
        $$quote($$BASEDIR/src/Pebble/Talk2WatchApi.h) \
        $$quote($$BASEDIR/src/PhoneActive/PhoneActive.h) \
        $$quote($$BASEDIR/src/PhysicalButtons/PhysicalButtons.h) \
        $$quote($$BASEDIR/src/PpsWatch/PpsWatch.h) \
        $$quote($$BASEDIR/src/ProgressStatus/ProgressStatus.h) \
        $$quote($$BASEDIR/src/RadioManager/RadioManager.h) \
        $$quote($$BASEDIR/src/ReconditionInfo/ReconditionInfo.h) \
        $$quote($$BASEDIR/src/SystemSettings/SystemSettings.h) \
        $$quote($$BASEDIR/src/TimeZone/TimeZone.h) \
        $$quote($$BASEDIR/src/WifiWatcher/WifiWatcher.h) \
        $$quote($$BASEDIR/src/applicationui.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/AndroidStatus/*.c) \
        $$quote($$BASEDIR/../src/AndroidStatus/*.c++) \
        $$quote($$BASEDIR/../src/AndroidStatus/*.cc) \
        $$quote($$BASEDIR/../src/AndroidStatus/*.cpp) \
        $$quote($$BASEDIR/../src/AndroidStatus/*.cxx) \
        $$quote($$BASEDIR/../src/AppLauncher/*.c) \
        $$quote($$BASEDIR/../src/AppLauncher/*.c++) \
        $$quote($$BASEDIR/../src/AppLauncher/*.cc) \
        $$quote($$BASEDIR/../src/AppLauncher/*.cpp) \
        $$quote($$BASEDIR/../src/AppLauncher/*.cxx) \
        $$quote($$BASEDIR/../src/ApplicationWindowSize/*.c) \
        $$quote($$BASEDIR/../src/ApplicationWindowSize/*.c++) \
        $$quote($$BASEDIR/../src/ApplicationWindowSize/*.cc) \
        $$quote($$BASEDIR/../src/ApplicationWindowSize/*.cpp) \
        $$quote($$BASEDIR/../src/ApplicationWindowSize/*.cxx) \
        $$quote($$BASEDIR/../src/Backlight/*.c) \
        $$quote($$BASEDIR/../src/Backlight/*.c++) \
        $$quote($$BASEDIR/../src/Backlight/*.cc) \
        $$quote($$BASEDIR/../src/Backlight/*.cpp) \
        $$quote($$BASEDIR/../src/Backlight/*.cxx) \
        $$quote($$BASEDIR/../src/BatteryManager/*.c) \
        $$quote($$BASEDIR/../src/BatteryManager/*.c++) \
        $$quote($$BASEDIR/../src/BatteryManager/*.cc) \
        $$quote($$BASEDIR/../src/BatteryManager/*.cpp) \
        $$quote($$BASEDIR/../src/BatteryManager/*.cxx) \
        $$quote($$BASEDIR/../src/BatterySavingMode/*.c) \
        $$quote($$BASEDIR/../src/BatterySavingMode/*.c++) \
        $$quote($$BASEDIR/../src/BatterySavingMode/*.cc) \
        $$quote($$BASEDIR/../src/BatterySavingMode/*.cpp) \
        $$quote($$BASEDIR/../src/BatterySavingMode/*.cxx) \
        $$quote($$BASEDIR/../src/BluetoothWatcher/*.c) \
        $$quote($$BASEDIR/../src/BluetoothWatcher/*.c++) \
        $$quote($$BASEDIR/../src/BluetoothWatcher/*.cc) \
        $$quote($$BASEDIR/../src/BluetoothWatcher/*.cpp) \
        $$quote($$BASEDIR/../src/BluetoothWatcher/*.cxx) \
        $$quote($$BASEDIR/../src/CalendarUpcomingEvents/*.c) \
        $$quote($$BASEDIR/../src/CalendarUpcomingEvents/*.c++) \
        $$quote($$BASEDIR/../src/CalendarUpcomingEvents/*.cc) \
        $$quote($$BASEDIR/../src/CalendarUpcomingEvents/*.cpp) \
        $$quote($$BASEDIR/../src/CalendarUpcomingEvents/*.cxx) \
        $$quote($$BASEDIR/../src/CellularTechnologies/*.c) \
        $$quote($$BASEDIR/../src/CellularTechnologies/*.c++) \
        $$quote($$BASEDIR/../src/CellularTechnologies/*.cc) \
        $$quote($$BASEDIR/../src/CellularTechnologies/*.cpp) \
        $$quote($$BASEDIR/../src/CellularTechnologies/*.cxx) \
        $$quote($$BASEDIR/../src/CountryCode/*.c) \
        $$quote($$BASEDIR/../src/CountryCode/*.c++) \
        $$quote($$BASEDIR/../src/CountryCode/*.cc) \
        $$quote($$BASEDIR/../src/CountryCode/*.cpp) \
        $$quote($$BASEDIR/../src/CountryCode/*.cxx) \
        $$quote($$BASEDIR/../src/DataRoaming/*.c) \
        $$quote($$BASEDIR/../src/DataRoaming/*.c++) \
        $$quote($$BASEDIR/../src/DataRoaming/*.cc) \
        $$quote($$BASEDIR/../src/DataRoaming/*.cpp) \
        $$quote($$BASEDIR/../src/DataRoaming/*.cxx) \
        $$quote($$BASEDIR/../src/DebugToken/*.c) \
        $$quote($$BASEDIR/../src/DebugToken/*.c++) \
        $$quote($$BASEDIR/../src/DebugToken/*.cc) \
        $$quote($$BASEDIR/../src/DebugToken/*.cpp) \
        $$quote($$BASEDIR/../src/DebugToken/*.cxx) \
        $$quote($$BASEDIR/../src/DeviceProperties/*.c) \
        $$quote($$BASEDIR/../src/DeviceProperties/*.c++) \
        $$quote($$BASEDIR/../src/DeviceProperties/*.cc) \
        $$quote($$BASEDIR/../src/DeviceProperties/*.cpp) \
        $$quote($$BASEDIR/../src/DeviceProperties/*.cxx) \
        $$quote($$BASEDIR/../src/FacedownAndPickup/*.c) \
        $$quote($$BASEDIR/../src/FacedownAndPickup/*.c++) \
        $$quote($$BASEDIR/../src/FacedownAndPickup/*.cc) \
        $$quote($$BASEDIR/../src/FacedownAndPickup/*.cpp) \
        $$quote($$BASEDIR/../src/FacedownAndPickup/*.cxx) \
        $$quote($$BASEDIR/../src/FileSystem/*.c) \
        $$quote($$BASEDIR/../src/FileSystem/*.c++) \
        $$quote($$BASEDIR/../src/FileSystem/*.cc) \
        $$quote($$BASEDIR/../src/FileSystem/*.cpp) \
        $$quote($$BASEDIR/../src/FileSystem/*.cxx) \
        $$quote($$BASEDIR/../src/FontSettings/*.c) \
        $$quote($$BASEDIR/../src/FontSettings/*.c++) \
        $$quote($$BASEDIR/../src/FontSettings/*.cc) \
        $$quote($$BASEDIR/../src/FontSettings/*.cpp) \
        $$quote($$BASEDIR/../src/FontSettings/*.cxx) \
        $$quote($$BASEDIR/../src/FullscreenPid/*.c) \
        $$quote($$BASEDIR/../src/FullscreenPid/*.c++) \
        $$quote($$BASEDIR/../src/FullscreenPid/*.cc) \
        $$quote($$BASEDIR/../src/FullscreenPid/*.cpp) \
        $$quote($$BASEDIR/../src/FullscreenPid/*.cxx) \
        $$quote($$BASEDIR/../src/HardwareInventory/*.c) \
        $$quote($$BASEDIR/../src/HardwareInventory/*.c++) \
        $$quote($$BASEDIR/../src/HardwareInventory/*.cc) \
        $$quote($$BASEDIR/../src/HardwareInventory/*.cpp) \
        $$quote($$BASEDIR/../src/HardwareInventory/*.cxx) \
        $$quote($$BASEDIR/../src/HubWatch/*.c) \
        $$quote($$BASEDIR/../src/HubWatch/*.c++) \
        $$quote($$BASEDIR/../src/HubWatch/*.cc) \
        $$quote($$BASEDIR/../src/HubWatch/*.cpp) \
        $$quote($$BASEDIR/../src/HubWatch/*.cxx) \
        $$quote($$BASEDIR/../src/LanguageAndInput/*.c) \
        $$quote($$BASEDIR/../src/LanguageAndInput/*.c++) \
        $$quote($$BASEDIR/../src/LanguageAndInput/*.cc) \
        $$quote($$BASEDIR/../src/LanguageAndInput/*.cpp) \
        $$quote($$BASEDIR/../src/LanguageAndInput/*.cxx) \
        $$quote($$BASEDIR/../src/PaymentMethod/*.c) \
        $$quote($$BASEDIR/../src/PaymentMethod/*.c++) \
        $$quote($$BASEDIR/../src/PaymentMethod/*.cc) \
        $$quote($$BASEDIR/../src/PaymentMethod/*.cpp) \
        $$quote($$BASEDIR/../src/PaymentMethod/*.cxx) \
        $$quote($$BASEDIR/../src/Pebble/*.c) \
        $$quote($$BASEDIR/../src/Pebble/*.c++) \
        $$quote($$BASEDIR/../src/Pebble/*.cc) \
        $$quote($$BASEDIR/../src/Pebble/*.cpp) \
        $$quote($$BASEDIR/../src/Pebble/*.cxx) \
        $$quote($$BASEDIR/../src/PhoneActive/*.c) \
        $$quote($$BASEDIR/../src/PhoneActive/*.c++) \
        $$quote($$BASEDIR/../src/PhoneActive/*.cc) \
        $$quote($$BASEDIR/../src/PhoneActive/*.cpp) \
        $$quote($$BASEDIR/../src/PhoneActive/*.cxx) \
        $$quote($$BASEDIR/../src/PhysicalButtons/*.c) \
        $$quote($$BASEDIR/../src/PhysicalButtons/*.c++) \
        $$quote($$BASEDIR/../src/PhysicalButtons/*.cc) \
        $$quote($$BASEDIR/../src/PhysicalButtons/*.cpp) \
        $$quote($$BASEDIR/../src/PhysicalButtons/*.cxx) \
        $$quote($$BASEDIR/../src/PpsWatch/*.c) \
        $$quote($$BASEDIR/../src/PpsWatch/*.c++) \
        $$quote($$BASEDIR/../src/PpsWatch/*.cc) \
        $$quote($$BASEDIR/../src/PpsWatch/*.cpp) \
        $$quote($$BASEDIR/../src/PpsWatch/*.cxx) \
        $$quote($$BASEDIR/../src/ProgressStatus/*.c) \
        $$quote($$BASEDIR/../src/ProgressStatus/*.c++) \
        $$quote($$BASEDIR/../src/ProgressStatus/*.cc) \
        $$quote($$BASEDIR/../src/ProgressStatus/*.cpp) \
        $$quote($$BASEDIR/../src/ProgressStatus/*.cxx) \
        $$quote($$BASEDIR/../src/RadioManager/*.c) \
        $$quote($$BASEDIR/../src/RadioManager/*.c++) \
        $$quote($$BASEDIR/../src/RadioManager/*.cc) \
        $$quote($$BASEDIR/../src/RadioManager/*.cpp) \
        $$quote($$BASEDIR/../src/RadioManager/*.cxx) \
        $$quote($$BASEDIR/../src/ReconditionInfo/*.c) \
        $$quote($$BASEDIR/../src/ReconditionInfo/*.c++) \
        $$quote($$BASEDIR/../src/ReconditionInfo/*.cc) \
        $$quote($$BASEDIR/../src/ReconditionInfo/*.cpp) \
        $$quote($$BASEDIR/../src/ReconditionInfo/*.cxx) \
        $$quote($$BASEDIR/../src/SystemSettings/*.c) \
        $$quote($$BASEDIR/../src/SystemSettings/*.c++) \
        $$quote($$BASEDIR/../src/SystemSettings/*.cc) \
        $$quote($$BASEDIR/../src/SystemSettings/*.cpp) \
        $$quote($$BASEDIR/../src/SystemSettings/*.cxx) \
        $$quote($$BASEDIR/../src/TimeZone/*.c) \
        $$quote($$BASEDIR/../src/TimeZone/*.c++) \
        $$quote($$BASEDIR/../src/TimeZone/*.cc) \
        $$quote($$BASEDIR/../src/TimeZone/*.cpp) \
        $$quote($$BASEDIR/../src/TimeZone/*.cxx) \
        $$quote($$BASEDIR/../src/WifiWatcher/*.c) \
        $$quote($$BASEDIR/../src/WifiWatcher/*.c++) \
        $$quote($$BASEDIR/../src/WifiWatcher/*.cc) \
        $$quote($$BASEDIR/../src/WifiWatcher/*.cpp) \
        $$quote($$BASEDIR/../src/WifiWatcher/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/QmlAccessor/*.qml) \
        $$quote($$BASEDIR/../assets/QmlAccessor/*.js) \
        $$quote($$BASEDIR/../assets/QmlAccessor/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
